name: portfolio
description: a portfolio page
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: ../design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2

flutter:
  uses-material-design: true

